#!/bin/bash

# Script copied from
# https://github.com/cirosantilli/linux-cheat/blob/master/ubuntu-18.04.1-desktop-amd64.sh
#
# Following the answer on StackOverflow
# https://askubuntu.com/a/1046792
#
# Modified to use Xubuntu 22.04 desktop amd64.

set -o errexit
set -o pipefail
set -o nounset

# defaults
THIS_SCRIPT="${0##*/}"
GUEST_OS="xubuntu-22.04-desktop-amd64"

# temps
T_QEMU_IMAGES_DIR=".local/qemu/images"

# print help doc
_help () {
	cat <<EOF
Usage: $THIS_SCRIPT [options]

Note: The guest OS ISO image must be pre-downloaded into pre-defined path ~/$T_QEMU_IMAGES_DIR

Options:
	[-g|--guest-os]
		Name of guest OS matching the iso file name

	TODO:
	[-r|--ram]
		System memory RAM size.
	[-d|--disk]
		Hard disk memory HDD size.
	[-c|--cpus]
		No of CPUs.
	[-f|--format]
		Guest OS valid output image format e.g. qcow2.
	[-s|--use-snapshot]
		Use provided snapshot if valid
	[--create-snapshot-on-exit]
		Creates snapshot on exit

Examples:
	* Using a default Guest OS '$GUEST_OS'
		$THIS_SCRIPT

	* Using any Guest OS
		$THIS_SCRIPT -g \$GUEST_OS
EOF
}

# echo before executing the commands
_exec () {
	echo "cmd: $@"
	"$@"
}

# parse command line args
while [[ $# -gt 0 ]]
do
	key="$1"
	case $key in
		-g|--guest-os)
			GUEST_OS="$2"
			shift
			;;
		*)
			echo "*** Invalid option '$1' see help doc below for examples ***"
			echo
			_help
			exit
			;;
	esac
	shift
done

qemu_images_dir="$HOME/$T_QEMU_IMAGES_DIR"
guest_iso="$qemu_images_dir/${GUEST_OS}.iso"

guest_disk_fmt='qcow2'
guest_disk_img="${qemu_images_dir}/${GUEST_OS}.img.${guest_disk_fmt}"
guest_disk_snapshot="${qemu_images_dir}/${GUEST_OS}.snapshot.${guest_disk_fmt}"

guest_ram='4G'
guest_cpus='4'
guest_hdd='40G'

# Go through installer manually.
if [ ! -f "$guest_disk_img" ]; then
	_exec \
		qemu-img create \
		-f "$guest_disk_fmt" \
		"$guest_disk_img" \
		$guest_hdd \
		;

	_exec \
		qemu-system-x86_64 \
		-cdrom "$guest_iso" \
		-drive "file=${guest_disk_img},format=${guest_disk_fmt}" \
		-enable-kvm \
		-m $guest_ram \
		-smp $guest_cpus \
		;
fi

# Snapshot the installation.
if [ ! -f "$guest_disk_snapshot" ]; then
	_exec \
		qemu-img create \
		-b "$guest_disk_img" \
		-f "$guest_disk_fmt" \
		-F "$guest_disk_fmt" \
		"$guest_disk_snapshot" \
		;
fi

# Run the installed image.
_exec \
	qemu-system-x86_64 \
	-drive "file=${guest_disk_snapshot},format=${guest_disk_fmt}" \
	-enable-kvm \
	-m $guest_ram \
	-serial mon:stdio \
	-smp $guest_cpus \
	-audiodev id=pa,driver=pa \
	-vga virtio \
	-cpu host \
	;
